sonar.projectKey=ic-devsecops-pipeline
sonar.projectName=ic-devsecops-pipeline
sonar.organization=ananddwivedi2013-nm8UY@github
sonar.sources=app/
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/tests/**,**/wheels/**