sonar.projectKey=ic-devsecops-pipeline
sonar.projectName=ic-devsecops-pipeline
sonar.organization=ananddwivedi2013@gmail.com
sonar.sources=app/
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/tests/**,**/wheels/**
